src/Entity/Currency.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\EntityIdTrait;
use App\Repository\CurrencyRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CurrencyRepository::class)]
class Currency
{
    use EntityIdTrait;

    #[ORM\Column(type: Types::STRING, length: 32)]
    private ?string $currency_title = null;

    #[ORM\Column(type: Types::STRING, length: 3)]
    private ?string $code = null;

    #[ORM\Column(type: Types::STRING, length: 12, nullable: true)]
    private ?string $symbol_left = null;

    #[ORM\Column(type: Types::STRING, length: 12, nullable: true)]
    private ?string $symbol_right = null;

    public function getCurrencyTitle(): ?string
    {
        return $this->currency_title;
    }

    public function setCurrencyTitle(string $currency_title): self
    {
        $this->currency_title = $currency_title;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getSymbolLeft(): ?string
    {
        return $this->symbol_left;
    }

    public function setSymbolLeft(?string $symbol_left): self
    {
        $this->symbol_left = $symbol_left;

        return $this;
    }

    public function getSymbolRight(): ?string
    {
        return $this->symbol_right;
    }

    public function setSymbolRight(?string $symbol_right): self
    {
        $this->symbol_right = $symbol_right;

        return $this;
    }
}

src/Entity/Property.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\CityTrait;
use App\Entity\Traits\EntityIdTrait;
use App\Entity\Traits\EntityLocationTrait;
use App\Entity\Traits\EntityTimestampableTrait;
use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{
    use CityTrait;
    use EntityIdTrait;
    use EntityLocationTrait;
    use EntityTimestampableTrait;

    final public const INVERSED_BY = 'properties';

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private $author;

    #[ORM\ManyToOne(targetEntity: DealType::class, inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private $deal_type;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private $category;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private $slug;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private $bathrooms_number;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private $bedrooms_number;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private $max_guests;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private $show_map;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private $price;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private $price_type;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private $available_now;

    #[ORM\Column(type: Types::STRING, length: 255, options: ['default' => 'pending'])]
    private string $state = 'published';

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Photo::class, orphanRemoval: true)]
    #[ORM\OrderBy(['sort_order' => 'ASC'])]
    private $photos;

    #[ORM\ManyToMany(targetEntity: Feature::class, inversedBy: 'properties')]
    private $features;

    #[ORM\Column(type: Types::INTEGER)]
    private $priority_number;

    #[ORM\OneToOne(mappedBy: 'property', targetEntity: PropertyDescription::class, cascade: ['persist', 'remove'])]
    private $propertyDescription;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->features = new ArrayCollection();
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getDealType(): ?DealType
    {
        return $this->deal_type;
    }

    public function setDealType(?DealType $dealType): self
    {
        $this->deal_type = $dealType;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getBathroomsNumber(): ?int
    {
        return $this->bathrooms_number;
    }

    public function setBathroomsNumber(?int $bathrooms_number): self
    {
        $this->bathrooms_number = $bathrooms_number;

        return $this;
    }

    public function getBedroomsNumber(): ?int
    {
        return $this->bedrooms_number;
    }

    public function setBedroomsNumber(?int $bedrooms_number): self
    {
        $this->bedrooms_number = $bedrooms_number;

        return $this;
    }

    public function getShowMap(): ?bool
    {
        return $this->show_map;
    }

    public function setShowMap(?bool $show_map): self
    {
        $this->show_map = $show_map;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPriceType(): ?string
    {
        return $this->price_type;
    }

    public function setPriceType(?string $price_type): self
    {
        $this->price_type = $price_type;

        return $this;
    }

    public function getAvailableNow(): ?bool
    {
        return $this->available_now;
    }

    public function setAvailableNow(?bool $available_now): self
    {
        $this->available_now = $available_now;

        return $this;
    }

    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setProperty($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getProperty() === $this) {
                $photo->setProperty(null);
            }
        }

        return $this;
    }

    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Feature $feature): self
    {
        if (!$this->features->contains($feature)) {
            $this->features[] = $feature;
        }

        return $this;
    }

    public function removeFeature(Feature $feature): self
    {
        if ($this->features->contains($feature)) {
            $this->features->removeElement($feature);
        }

        return $this;
    }

    public function getPriorityNumber(): ?int
    {
        return $this->priority_number;
    }

    public function setPriorityNumber(?int $priority_number): self
    {
        $this->priority_number = $priority_number;

        return $this;
    }

    public function getMaxGuests(): ?int
    {
        return $this->max_guests;
    }

    public function setMaxGuests(?int $max_guests): self
    {
        $this->max_guests = $max_guests;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function isPublished(): bool
    {
        return 'published' === $this->state;
    }

    public function getPropertyDescription(): ?PropertyDescription
    {
        return $this->propertyDescription;
    }

    public function setPropertyDescription(PropertyDescription $propertyDescription): self
    {
        // set the owning side of the relation if necessary
        if ($propertyDescription->getProperty() !== $this) {
            $propertyDescription->setProperty($this);
        }

        $this->propertyDescription = $propertyDescription;

        return $this;
    }
}

src/Controller/Admin/PropertyController.php
<?php

declare(strict_types=1);

namespace App\Controller\Admin;

use App\Controller\BaseController;
use App\Entity\Property;
use App\Form\Type\PropertyType;
use App\Repository\FilterRepository;
use App\Service\Admin\PropertyService;
use App\Transformer\RequestToArrayTransformer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Component\Security\Http\Attribute\IsGranted;

final class PropertyController extends BaseController
{
    #[Route(path: '/admin/property', name: 'admin_property', defaults: ['page' => 1], methods: ['GET'])]
    public function index(
        Request $request,
        FilterRepository $repository,
        RequestToArrayTransformer $transformer
    ): Response {
        $searchParams = $transformer->transform($request);
        $properties = $repository->findByFilter($searchParams);

        return $this->render('admin/property/index.html.twig', [
            'site' => $this->site($request),
            'properties' => $properties,
            'searchParams' => $searchParams,
        ]);
    }

    #[Route(path: '/admin/property/new', name: 'admin_property_new')]
    public function new(Request $request, PropertyService $service): Response
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $service->create($property);

            return $this->redirectToRoute('admin_photo_edit', ['id' => $property->getId()]);
        }

        return $this->render('admin/property/new.html.twig', [
            'site' => $this->site($request),
            'property' => $property,
            'form' => $form,
        ]);
    }

    /**
     * Displays a form to edit an existing Property entity.
     */
    #[Route(
        path: '/admin/property/{id}/edit',
        name: 'admin_property_edit',
        requirements: ['id' => Requirement::POSITIVE_INT],
        methods: ['GET', 'POST']
    )]
    public function edit(Request $request, Property $property, PropertyService $service): Response
    {
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $service->update($property);

            return $this->redirectToRoute('admin_property');
        }

        return $this->render('admin/property/edit.html.twig', [
            'site' => $this->site($request),
            'form' => $form,
        ]);
    }

    /**
     * Deletes a Property entity.
     */
    #[Route(
        path: '/property/{id}/delete',
        name: 'admin_property_delete',
        requirements: ['id' => Requirement::POSITIVE_INT],
        methods: ['POST']
    )]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Request $request, Property $property, PropertyService $service): Response
    {
        if (!$this->isCsrfTokenValid('delete', $request->getPayload()->get('token'))) {
            return $this->redirectToRoute('admin_property');
        }

        $service->delete($property);

        return $this->redirectToRoute('admin_property');
    }
}

src/Controller/Ajax/User/PropertyController.php
<?php

declare(strict_types=1);

namespace App\Controller\Ajax\User;

use App\Controller\Ajax\AjaxController;
use App\Entity\Property;
use App\Repository\UserPropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Component\Security\Http\Attribute\IsGranted;

final class PropertyController extends AbstractController implements AjaxController
{
    #[Route(
        path: '/user/property/{id}/update',
        name: 'user_property_update',
        requirements: ['id' => Requirement::POSITIVE_INT],
        methods: ['GET']
    )]
    #[IsGranted('PROPERTY_EDIT', subject: 'property', message: 'You cannot change this property.')]
    public function update(Request $request, Property $property, UserPropertyRepository $repository): JsonResponse
    {
        $state = $request->query->get('state');

        if (!\in_array($state, ['published', 'private'], true)) {
            return new JsonResponse(['status' => 'fail'], Response::HTTP_UNPROCESSABLE_ENTITY);
        }

        if ($repository->changeState($property, $state)) {
            return new JsonResponse(['status' => 'ok']);
        }

        return new JsonResponse(['status' => 'fail'], Response::HTTP_INTERNAL_SERVER_ERROR);
    }
}

src/Controller/PropertyController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Property;
use App\Repository\FilterRepository;
use App\Repository\PropertyRepository;
use App\Repository\SimilarRepository;
use App\Service\URLService;
use App\Transformer\RequestToArrayTransformer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Component\Security\Http\Attribute\IsGranted;

final class PropertyController extends BaseController
{
    #[Route(path: '/', name: 'property', defaults: ['page' => 1], methods: ['GET'])]
    public function search(
        Request $request,
        FilterRepository $repository,
        RequestToArrayTransformer $transformer
    ): Response {
        $searchParams = $transformer->transform($request);
        $properties = $repository->findByFilter($searchParams);

        return $this->render(
            'property/index.html.twig',
            [
                'site' => $this->site($request),
                'properties' => $properties,
                'searchParams' => $searchParams,
            ]
        );
    }

    #[Route(path: '/map', name: 'map_view', methods: ['GET'])]
    public function mapView(Request $request, PropertyRepository $repository): Response
    {
        return $this->render(
            'property/map.html.twig',
            [
                'site' => $this->site($request),
                'properties' => $repository->findAllPublished(),
            ]
        );
    }

    #[Route(
        path: '/{citySlug}/{slug}/{id}',
        name: 'property_show',
        requirements: ['id' => Requirement::POSITIVE_INT],
        methods: ['GET'])
    ]
    #[IsGranted(
        'PROPERTY_VIEW',
        subject: 'property',
        message: 'Properties can only be shown to their owners.'
    )]
    public function propertyShow(
        Request $request,
        URLService $url,
        Property $property,
        SimilarRepository $repository
    ): Response {
        if (!$url->isCanonical($property, $request)) {
            return $this->redirect($url->generateCanonical($property), Response::HTTP_MOVED_PERMANENTLY);
        } elseif ($url->isRefererFromCurrentHost($request)) {
            $showBackButton = true;
        }

        return $this->render(
            'property/show.html.twig',
            [
                'site' => $this->site($request),
                'property' => $property,
                'properties' => $repository->findSimilarProperties($property),
                'number_of_photos' => \count($property->getPhotos()),
                'show_back_button' => $showBackButton ?? false,
            ]
        );
    }
}

templates/property/index.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ site.meta_title }}{{ searchParams.page|page }}{% endblock %}

{% block description %}{{ site.meta_description }}{{ searchParams.page|page }}{% endblock %}

{% block header %}
    {{ include('property/partials/_search_form.html.twig') }}
{% endblock %}

{% block body %}

    {% if is_granted('ROLE_ADMIN') %}

        <a href="{{ url('admin_property_new') }}" class="btn btn-primary float">
            <i class="fas fa-plus float-icon"></i>
        </a>

    {% elseif is_granted('ROLE_USER') %}

        <a href="{{ url('user_property_new') }}" class="btn btn-primary float">
            <i class="fas fa-plus float-icon"></i>
        </a>

    {% endif %}

    <div class="row">
        <div class="col-lg-6 col-sm-12">
            <h1 class="h3">{{ site.title }}</h1>
        </div>
        <div class="col-lg-6 col-sm-12 text-right">
            <a href="{{ path('map_view') }}" class="btn btn-sm btn-light icon-green">
                <i class="fas fa-map-marker-alt"></i> {{ 'show_on_map'|trans }}
            </a>
        </div>
    </div>

    <br>
    <div class="row">

        {% for property in properties %}

            <!-- Item -->
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card full-xs">

                    <div class="property-box-img">

                        <a href="{{ path('property_show', {
                            'id':  property.id,
                            'citySlug': property.city.slug,
                            'slug': property.slug}) }}">

                            {% for photo in property.photos | slice(0, 1) %}

                                <img class="card-img-top lazyload" src="{{ asset('/images/transparent.png') }}"
                                     data-src="/uploads/images/small/{{ photo.photo }}"
                                     alt="{{ property.address }}"
                                     title="{{ property.address }}"/>

                            {% else %}

                                <img class="card-img-top border-bottom" src="{{ asset('/images/no-photo.png') }}"
                                     alt="{{ property.address }}"
                                     title="{{ property.address }}"/>

                            {% endfor %}

                            {% if property.price != '' %}
                                <span class="price">
                                    {{ site.currency.symbolLeft }}{{ property.price }}
                                    {{ site.currency.symbolRight }}

                                    {% if property.priceType != '' %}
                                        / {{ property.priceType }}
                                    {% endif %}
                                </span>
                            {% endif %}
                        </a>
                    </div>

                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{ path('property_show', {
                                'id':  property.id,
                                'citySlug': property.city.slug,
                                'slug': property.slug}) }}">
                                {{ property.propertyDescription.title }}
                            </a>
                        </h5>
                        <p class="small icon-green">
                            <i class="fas fa-map-marker-alt"></i> {{ property.address }}
                        </p>

                        {% if property.metroStation %}
                            <p class="small icon-green">
                                <i class="fas fa-subway"></i> {{ property.metroStation.name }}
                            </p>
                        {% endif %}

                        <span class="attribute">{{ property.dealType.name }}</span>
                        <span class="attribute">{{ property.category.name }}</span>

                        {% if property.bedroomsNumber %}
                            <span
                                class="attribute">{{ 'property.bedrooms'|trans }}: {{ property.bedroomsNumber }}</span>
                        {% endif %}
                    </div>
                </div>
                <br>
            </div>
            <!-- / Item -->

        {% else %}
            <div class="col-sm-12">
                {{ 'no_items_found' | trans }}
            </div>
        {% endfor %}

    </div>

    {{ knp_pagination_render(properties) }}

{% endblock %}

templates/property/map.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ "title.properties_on_map"|trans }}{% endblock %}

{% block description %}{{ site.meta_description }}{% endblock %}

{% block body %}

    {% if is_granted('ROLE_ADMIN') %}

        <a href="{{ url('admin_map_settings') }}" class="btn btn-primary float">
            <i class="fas fa-cog float-icon"></i>
        </a>

    {% endif %}

    {% if site.ymaps_key != '' %}

        <script src="https://api-maps.yandex.ru/2.1/?apikey={{ site.ymaps_key }}&lang={{ app.request.locale }}"></script>

    {% else %}

        <script src="https://api-maps.yandex.ru/2.1/?lang={{ app.request.locale }}"></script>

    {% endif %}

    <script>
        ymaps.ready(init);

        function init() {
            var myMap = new ymaps.Map("map", {
                center: [{{ site.map_center|default('27.188534, -81.128735') }}],
                zoom: {{ site.map_zoom|default('7') }}
            });

            {% for property in properties %}

            var myGeoObject = new ymaps.GeoObject({
                geometry: {
                    type: "Point",
                    coordinates: [{{ property.latitude }}, {{ property.longitude }}]
                },
                properties: {
                    hintContent: "{{ site.currency.symbolLeft }}{{ property.price }} {{ site.currency.symbolRight }}",
                    balloonContentHeader: "{{ site.currency.symbolLeft }}{{ property.price }} {{ site.currency.symbolRight }}",
                    balloonContentBody: "{{ property.category.name }}<br><a href=\"{{ path('property_show', {
                        'id':  property.id,
                        'citySlug': property.city.slug,
                        'slug': property.slug}) }}\">{{ 'view_details'|trans }}</a>",
                }
            }, {preset: "islands#blueHomeIcon"});

            myMap.geoObjects.add(myGeoObject);

            {% endfor %}

        }

    </script>

    <div id="map" class="mb-3 mt-3"></div>

{% endblock %}

templates/property/show.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ property.propertyDescription.metaTitle|default(property.propertyDescription.title) }}{% endblock %}
{% block description %}{{ property.propertyDescription.metaDescription }}{% endblock %}

{% block stylesheets %}

    {{ encore_entry_link_tags('css/detail') }}
    {{ encore_entry_link_tags('css/ekko-lightbox') }}

    {% if site.show_bottom_bar == '1' %}
        {{ encore_entry_link_tags('css/bottom-bar') }}
    {% endif %}

{% endblock %}

{% block header %}{% endblock %}

{% block body %}

    {% if is_granted('ROLE_ADMIN') %}

        <a href="{{ url('admin_property_edit', {id: property.id}) }}" class="btn btn-primary float">
            <i class="fas fa-pen float-icon"></i>
        </a>

    {% endif %}

    <br>
    <div class="row">
        <div class="col-md-8">
            <div class="card full-xs mb-4">

                {{ include('property/partials/_slider.html.twig') }}

                <div class="card-body">

                    <h4 class="card-title">{{ property.propertyDescription.title }}</h4>

                    <p class="address">{{ property.address }}</p>

                    {{ include('property/partials/_overview.html.twig') }}

                    {{ property.propertyDescription.content | raw }}

                    <div class="clearfix"></div>

                    <div class="row">
                        {% for feature in property.features %}
                            <div class="col-lg-4 col-md-6 col-sm-6 icon-green">
                                {{ feature.icon|default('<i class="fas fa-check"></i>')|raw }}
                                {{ feature.name }}
                            </div>
                        {% endfor %}
                    </div>

                    <div id="map"
                         data-balloonContent="{{ property.propertyDescription.title }}"
                         data-hintContent="{{ property.category.name }}"
                         data-latitude="{{ property.latitude }}"
                         data-longitude="{{ property.longitude }}"
                    ></div>

                </div>
            </div>
        </div>

        <!-- Sidebar -->
        <div class="col-md-4">

            {{ include('property/partials/_contact_widget.html.twig') }}
            {{ include('property/partials/_search_widget.html.twig') }}

        </div>

    </div>

    {% if properties %}
        {{ include('property/partials/_similar_properties.html.twig') }}
    {% endif %}

{% endblock %}

{% block javascripts %}

    {{ encore_entry_script_tags('js/ekko-lightbox') }}

    {% if property.showMap == true and property.latitude != '' and property.longitude != '' %}

        {% if site.ymaps_key != '' %}

            <script src="https://api-maps.yandex.ru/2.1/?apikey={{ site.ymaps_key }}&lang={{ app.request.locale }}"></script>

        {% else %}

            <script src="https://api-maps.yandex.ru/2.1/?lang={{ app.request.locale }}"></script>

        {% endif %}

        {{ encore_entry_script_tags('js/map') }}

    {% endif %}

    {% if site.show_bottom_bar == '1' %}
        {{ encore_entry_script_tags('js/bottom-bar') }}
    {% endif %}

{% endblock %}