src/Entity/Menu.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\EntityIdTrait;
use App\Repository\MenuRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Table]
#[ORM\UniqueConstraint(name: 'url_locale_unique_key', columns: ['url', 'locale'])]
#[ORM\Entity(repositoryClass: MenuRepository::class)]
#[UniqueEntity(['url', 'locale'])]
class Menu
{
    use EntityIdTrait;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::STRING, length: 2)]
    private string $locale;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $sort_order = null;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private ?string $url = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private ?bool $nofollow = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private ?bool $new_tab = null;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSortOrder(): ?int
    {
        return $this->sort_order;
    }

    public function setSortOrder(?int $sort_order): self
    {
        $this->sort_order = $sort_order;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getNofollow(): ?bool
    {
        return $this->nofollow;
    }

    public function setNofollow(?bool $nofollow): self
    {
        $this->nofollow = $nofollow;

        return $this;
    }

    public function getNewTab(): ?bool
    {
        return $this->new_tab;
    }

    public function setNewTab(?bool $new_tab): self
    {
        $this->new_tab = $new_tab;

        return $this;
    }

    public function getLocale(): string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }
}

templates/layout/partials/_locale_switcher.html.twig
{% if site.show_language_selector == '1' %}

    {% set route = app.request.attributes.get('_route') %}
    {% set route_params = app.request.attributes.get('_route_params') %}
    {% set params = route_params|merge(app.request.query.all) %}
    {% set current_language = app.request.locale|locale_name(app.request.locale)|u.title %}

    <li class="nav-item dropdown{% if no_arrow is defined and no_arrow %} no-arrow{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown-language" role="button"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{{ asset('images/languages/' ~ app.request.locale ~ '.png') }}"
                 alt="{{ current_language }}"/> {{ current_language }}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-language">
            {% for locale in locales|split('|') %}
                {% if locale is not same as(app.request.locale) %}
                    {% set language = locale|locale_name(locale)|u.title %}
                    <a class="dropdown-item"
                       href="{% if route == 'default_route' %}/{{ locale }}{% else %}{{ path(route, params|merge({ _locale: locale })) }}{% endif %}">
                        <img src="{{ asset('images/languages/' ~ locale ~ '.png') }}"
                             alt="{{ language }}"/> {{ language }}
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </li>

{% endif %}

templates/layout/partials/_navbar.html.twig
<nav class="navbar {% if site.fixed_top_navbar == '1' %}fixed-top{% endif %} navbar-expand-lg navbar-light bg-white">

    {% if show_back_button|default(false) %}
        <a class="navbar-brand" href="javascript: history.back()">
            <i class="fas fa-arrow-left"></i> {{ 'menu.back'|trans }}
        </a>
    {% else %}
        <a class="navbar-brand" href="{{ path('property') }}">
            {% if site.logo_image == '' %}
                {{ site.name }}
            {% else %}
                <img src="{{ asset('uploads/images/full/' ~ site.logo_image) }}" alt="{{ site.name }}">
            {% endif %}
        </a>
    {% endif %}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            {% for item in site.menu %}

                {% if (item.url == '/' and locale == item.locale) %}
                    {% set url = '/' %}
                {% elseif ('https://' not in item.url) %}
                    {% set url = '/' ~ item.locale ~ item.url %}
                {% else %}
                    {% set url = item.url %}
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="{{ url }}"
                        {% if item.nofollow == true %} rel="nofollow" {% endif %}
                        {% if item.newTab == true %} target="_blank" {% endif %}
                    >
                        {{ item.title }}
                    </a>
                </li>

            {% endfor %}
        </ul>

        <ul class="navbar-nav ml-auto">
            {{ include('layout/partials/_locale_switcher.html.twig', {site: site}) }}

            {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle"
                       href="#" id="userDropdown"
                       role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false">
                        {{ 'menu.admin'|trans }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{{ path('admin_dashboard') }}">
                            {{ 'dashboard'|trans }}
                        </a>
                        <a class="dropdown-item" href="{{ path('user_property') }}">
                            {{ 'menu.account'|trans }}
                        </a>
                        <a class="dropdown-item" href="{{ path('admin_user_edit', {id: app.user.id}) }}">
                            {{ 'menu.edit_profile'|trans }}
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ path('security_logout') }}">
                            {{ 'menu.logout'|trans }}
                        </a>
                    </div>
                </li>
            {% elseif is_granted('ROLE_USER') %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('user_property') }}">{{ 'menu.account'|trans }}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('security_login') }}">{{ 'menu.login'|trans }}</a>
                </li>

                {% if '1' == site.anyone_can_register %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('register') }}">{{ 'menu.register'|trans }}</a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>

    </div>
</nav>